### ISSUE TITLE
FEATURE - EXT - Smart Home Page

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#232]
As a user , I would like to be presented with some Guided Answers that would be relevant to me 

### Description

The smart home page will contain the following 

-  The users last visited Guided Answer
- The users bookmarks
- Users should be able to execute a free search on Guided Answers content
- Users should be able to remove bookmarks they are no longer interested in.  
- Users should be presented with quick filters derived based on the development space set up - extensions, projects etc. (Phase 2)
- Users should be presented with suggested Guided Answers based on Guided Answer content creators choice ( Phase 3) 

There will be a separate section for last visited, bookmarks, suggested guides and quick filters. If there is no content available for these sections the section will simply not show. 

The smart home page could be delivered in phases

1. Phase 1 - Centered Search, last visited and bookmarks
2. Phase 2 - Add Quick filters 
3. Phase 3 - Add Suggested Content

Concerns from Grooming

How does the user return to the Smart Home page after clicking on a bookmark , last visited or executing a search?

When a user has executed a free search , selects a Guided Answer and clicks on the 'Home ' page are they returned to the new Smart Home page or the returned list from their free search? 

When a user clears the search what should the user see the Smart Home page or a list of guided answers like we currently show? 

Can you remove a bookmark from the Home screen?

What happens in SBAS  for the Fiori Dev Space?  Should implement quick filters to show the filters that is applied? 

This should be broken in to user stories for each phase. 

### Technical Design

The last 5 guided answers visited will be stored but only the last one will be displayed to the user. 

Quick Filters is Dependent on Environment Analyser to determine dev space 

###Visual Design 
Search is centered aligned
Content is shown in 2 columns beneath the centered search

https://www.figma.com/file/XSZw3w81MYY0QPe1BoUcBO/Guided-Answers?node-id=0%3A1

<img width="601" alt="Screenshot 2023-06-16 at 17 00 19" src="https://github.com/SAP/guided-answers-extension/assets/9609226/a09e3c32-6467-48f9-8626-83e6f4684f60">
<img width="612" alt="Screenshot 2023-06-16 at 17 00 27" src="https://github.com/SAP/guided-answers-extension/assets/9609226/f7361f25-b07b-47f4-9b60-ad844a5d8b30">
<img width="619" alt="Screenshot 2023-06-16 at 17 00 35" src="https://github.com/SAP/guided-answers-extension/assets/9609226/2391ba9c-d477-4d25-af07-003e97e571fb">

### Interaction Design

Phase 1 
1. Users Opens GA - Smart Home Page is displayed a centered search input field
2. User searches for a guide 
3. User selects a guide
4. User navigates through a guide 
5. User bookmarks a guide
6. User clicks Home - What happens ? Search result list or new Smart Home page? 
7. User closes GA 
8. User opens GA - Smart Home Page is displayed with a centered search input field, last visited guided displaying and bookmark
9. User removes bookmark - as only one bookmark the bookmark section disappears
10. Users clicks last visited - User is navigated to that node
11. User navigates to another node in that tree - Last updated guided is updated
13. User clicks 'Home' - What happens???
14. User closes GA
15. User opens GA - Smart Home Page is displayed showing centered search and last visited guid
16. User enters input in search input field- Search results are displayed 
17. User clears search input field - What happens? User sees empty search list or new Smart Home page? 

### Acceptance Criteria
1.  When user opens GA a new home page is displayed to the user ( Blank state / Populated State ) 
2. User can view last visited guides ( phase 1 ) 
3. User can view bookmarks ( phase 1 ) 
4. User view suggested guides ( Phase 3 ) 
5. User view quick filters ( Phase 2) 
6. User  Execute a free search
7. User can return to the home page navigating through a guide?? How? ? 

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by gpeuc** [comment]
## Homepage
- - - - -

The general idea is to have search-only focused Home, because we can't do much else, seeing that we are not loading any results beforehand. So, let's just have Google-style home, with prominent search field.

Additionally, it appears we can get some information about user's workspace, and can suggest some search results upfront. That's what the pills below are. We can stack more of them if we know more about the surrounding area the user is in. We could also be a bit sneaky and hard-code "SAP Fiori tools" as a search term at the top. Clicking those just triggers the search for that term and takes the user to the Search Results Page.

## Search results page
- - - - - -

I have updated it slightly with search box being left aligned now.

The terms that the user searched on the Home is carried over, and is in the search box.

This page will always have some results displayed (unless search is invalid, we have an illustration for that) and we can light up the two filters then.

Clicking on the logo (SAP logo and Guided Answers text) takes users back to the Homepage.

## Other pages
- - - - -

On any of the Guide pages, clicking Back (if on the first page), or clicking Home icon should take the users to Search results page, and we should **remember** what the user searched and load those results. This is to enable users to click through couple of the results quickly, without having to search again and again in case they've got the wrong result.

**Comment by carwelsh** [comment]
@gpeuc - Quick question Goran, how would the user go from the search result page to the Home page ? or do not allow this once they have entered free search or selected a pill?

**Comment by gpeuc** [comment]
<img width="1105" alt="Screenshot 2022-09-19 at 12 50 07" src="https://user-images.githubusercontent.com/44162846/191010920-7d7a537f-763a-4ead-8b0a-ffcc1aacb816.png">

**Comment by carwelsh** [comment]
@gpeuc - OOOps
