### ISSUE TITLE
BUG - UX- Max width (and truncation) for descriptions in search results

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#235]
These long texts are hard to read.

<img width="1667" alt="Screenshot 2022-09-09 at 15 11 27" src="https://user-images.githubusercontent.com/44162846/189369929-38a14661-f3da-4dde-920f-d336b1528d55.png">

That's why in the designs the text block for descriptions is capped at `700px`
 
<img width="806" alt="Screenshot 2022-09-09 at 15 12 07" src="https://user-images.githubusercontent.com/44162846/189370067-b4a328a1-7823-4f55-8764-dfbd7111ed7f.png">

- - - - -

We should also do something about these descriptions sometimes being really huge.

This is me setting the line-clamp to three lines and max-width to 700px:

<img width="1094" alt="Screenshot 2022-09-09 at 15 41 24" src="https://user-images.githubusercontent.com/44162846/189376288-616051b4-68ce-465a-9465-9c00198caf83.png">

Here's the code for `guided-answer__tree__desc`

```
color: var(--vscode-foreground);
height: auto;
font-size: 13px;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
display: -webkit-box;
line-height: 18px;
max-height: 54px;
text-overflow: ellipsis;
overflow: hidden;
max-width: 700px;
```

max-height is sort of redundant because line clamp keeps it at 3 lines, but I don't know, maybe leave it just in case 😄

**Comment by gpeuc** [comment]
@ritarora @unseen1980

**Comment by unseen1980** [comment]
@carwelsh This has already been fixed in this [PR](https://github.com/SAP/guided-answers-extension/pull/259/files#diff-e9eb3d4993dc04303a521ec8cd2307b6a564c07c68a99b3610163ddf7687d863R80). I just validated it.
<img width="1292" alt="Screenshot 2022-11-14 at 11 11 20" src="https://user-images.githubusercontent.com/2386570/201645943-20d6125c-7a03-4e32-80f0-e17fac041271.png">
