### ISSUE TITLE
FEATURE - API - Show list of guided answers when launching first time

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#37]
**As a user using Guided Answer extension in VSCode/SBAS and launching it first time
I want to see the list of Guided Answers right away ,
so that I can scroll up/down and browse through the list**

### Description

Currently if  a user launches Guided Answers extension, the list of guided answers is BLANK. The user currently has to enter search criteria to get results. 
We need the Guided Answer extension to show the user list of answers after first launch.
The list should not list ALL the guides in one go. Pagination should be introduced.
The list should also contain information that will help the user what guide to pick e.g. Product and component. Currently the returned list just returns the title and description.

### Technical Design
- Guided Answers API has to be enhanced to support the pagination OR for time being it can be done from UX side (though benefit might be less if we consider performance)

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a Guided Answers extension installed in VSCode/SBAS
**when** I execute the command `SAP: Open Guided Answers`
**then** I should see the list of guided answers

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by carwelsh** [comment]
See Goran's comments here #111

**Comment by carwelsh** [comment]
@Klaus-Keller - In yesterday's call you mentioned there is away to display a list without the need to update the API. Is it search for an empty string ? 

@sanat-thukral FYI

**Comment by gpeuc** [comment]
Yeah, thanks @carwelsh 😄 

If we can (technically, legally, and morally) we should pin our guide at the top. But yeah, we should load some guides!

**Comment by gpeuc** [comment]
Purely mathematically speaking, showing some results is better than showing no results. If we show some, there's at least a chance users will see some interesting guide. If we show nothing - they won't. 

But more importantly, if we show something the users will at least know what that page is about, we will immediately set some expectations and samples. Rather than asking users to search for something and they have no clue what's even in there. 

From any angle, the UX of having stuff here is much better than not having stuff here. 

As for performance, yeah, we need to figure it out, that's why the original GA app only loads 20 and then Lazy Loads more on scroll.
